Update workflow and Makefile

diff --git a/.github/workflows/mixins.yaml b/.github/workflows/mixins.yaml
--- a/.github/workflows/mixins.yaml
+++ b/.github/workflows/mixins.yaml
@@ -14,18 +14,31 @@ jobs:
           ref: ${{ github.event.pull_request.head.sha }}
           persist-credentials: true
 
+      - name: Update Jsonnet dependencies
+        if: ${{ github.actor == 'renovate[bot]' }}
+        run: make vendor
+        env:
+          JB_ARGS: update
+
       - name: Render mixins
         run: make
 
-      - name: Push changes
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@noreply.github.com"
-          git add .
+      - name: Get status
+        run: echo "changed=$(git status --short | grep -c -E "docs|jsonnetfile.lock.json")" >> "$GITHUB_OUTPUT"
+        id: status
 
-          if git diff --staged --quiet; then
-            echo "No changes detected. Skipping ..."
-          else
-            git commit -m "Update rendered mixins"
-            git push
-          fi
+      - name: Push changes
+        if: ${{ github.actor == 'renovate[bot]' && steps.status.outputs.changed !=0 }}
+        run: |
+          git add docs jsonnetfile.lock.json
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git commit -m "Update files after Renovate update"
+          git push origin HEAD:refs/heads/${{ github.event.pull_request.head.ref }}
+
+      - name: Detected changes
+        if: ${{ github.actor != 'renovate[bot]' && steps.status.outputs.changed !=0 }}
+        run: |
+          echo "::error::Detected changes in the rendered docs files. Please run 'make' locally and commit the changes."
+          git status --short docs
+          exit 1
